Only keep cursor out of regular checkboxes
vslinko/obsidian-outliner pull request #403
Opened 2022-12-19 20:29 UTC by sitaktif

Keeping the cursor out of regular checkboxes (`[ ]` and `[x]`) does not allow the user to edit the contents directly, but this is not an issue because one can use the "Toggle checkbox status" command (bound to Cmd-L or Ctrl-L by default).

On the other hand, keeping the cursor out of any custom checkboxes (e.g. `[!]`) prevents the user from editing it and causes issues.

Moreover, we were previously considering e.g. `[[]` a custom checkbox (with character `[` inside the "box"), which caused additional problems when a link is added just after a bullet point (`[[]]`).

Fixes #402

2022-12-19 20:30 UTC, sitaktif commented
@vslinko this fixes the issue, sorry :-(

2022-12-19 20:34 UTC, sitaktif commented
Note: this only fixes the original issue reported on #402.

I'll need more time to look at the other issues - maybe it's worth reverting the change I submitted for checkbox handling (suggested [here](https://github.com/vslinko/obsidian-outliner/issues/402#issuecomment-1358273536) too).

2022-12-19 20:38 UTC, vslinko requested changes

2022-12-19 20:38 UTC, vslinko commented on src/services/ParserService.ts
> +const optionalCheckbox = `(?:\\[[ xX]\\]\\s?)?`;
I suggest a different solution that should cover more use cases:

```js
const optionalCheckbox = `(?:\\[[^\\[\\]]\\]( |\t))?`;
```

2022-12-19 21:03 UTC, sitaktif commented on src/services/ParserService.ts
> +const optionalCheckbox = `(?:\\[[ xX]\\]\\s?)?`;
That was my initial change but I think it might be a bad idea because it will prevent people from editing it.

E.g. how do you edit the checkbox in...

```
- [!] something
```

...if your cursor can't reach the `!` (and if you don't have a hotkey to change the status)?

---

Ha, and now I realise there's yet another issue which affects custom-checkbox users _even_ if we only move the cursor for regular checkboxes: as a user, how do you change `- [ ] something` to `- [!] something` if your cursor can't reach the box?

For this last one, a possibility is to have another option for moving the cursor 1/ never 2/ only for bullets 3/ for bullets and checkboxes.

2022-12-19 21:33 UTC, sitaktif commented
Last commit fixes the second test.

There is still an issue related to Cmd-a / Ctrl-a, but technically this isssue was present before my change.

(Ironically, my first approach to solving "keep the cursor outside the checkbox" fixed Cmd-a/Ctrl-a but caused other issues so I had to abandon it. The second approach unfortunately "un-fixed" Cmd-a/Ctrl-a without me realising).

2022-12-19 21:40 UTC, sitaktif commented
@vslinko I'm in GMT timezone, so in the interest of fixing users asap, feel free to do anything you feel would help without asking me first (including merging this change yourself, possibly modifying it according to your suggestion above etc.).

2022-12-20 08:07 UTC, vslinko approved these changes

2022-12-20 08:09 UTC, merged